### ISSUE TITLE
Modificaciones en el README

### ISSUE THREAD

**Issue by alu0100816761** [ULL-ESIT-GRADOII-PL/object-oriented-programming-in-js-alexisnatalie#2]
Te parece correcto ayudarnos de unas imagenes para documentar en el README? @alu0100818369

**Comment by alu0100818369** [comment]
@alu0100816761 me parece muy bien, también podríamos comentar un poco la estructura de nuestra expresión regular (como la dividimos, porqué, ...)

**Comment by alu0100816761** [comment]
@alu0100818369 Me parece correcto, implementémoslo. Cierro el issue.
